/* Exemplo para o exercício da Aula 3 de Operadores lógicos e relacionais, Controle de fluxo e blocos. */


public class Main {

  public static void main(String[] args) {

    ifFlecha();
    ifSemFlexa();
    ifFerias();
    ifMnor();

    switchSemana();
    switchNumero();
    switchFerias();

  }

  private static void ifFlecha() {

    int mes = 9;
    if (mes == 1) {
      System.out.println("Janeiro");
    } else {
      if (mes == 2) {
        System.out.println("Fevereiro");
      } else {
        if (mes == 3) {
          System.out.print
        }
      }
    }
  }
}