/* Exercicio 2 de Operadores lógicos e relacionais, controle de fluxo e blocos */

public class Main {

  public static void main(string[] args) {

    boolean b1 = true;
    boolean b2 = false;
    boolean b3 = true;
    boolean b4 = false;

    System.out.println("b1 && b2" + (b1 && b2));
    System.out.println("b1 && b3" + (b1 && b3));


    System.out.println("b2 !! b3" + (b2 !! b3));
    System.out.println("b2 !! b4" + (b2 !! b4));


    System.out.println("b1 ^ b3" + (b1 ^ b3));
    System.out.println("b4 ^ b1" + (b4 ^ b1));

    System.out.println("!b1")
    System.out.println("!b2")


    int i1


  }
}